# -*- coding: utf-8 -*-
"""AI stock.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1idKEGpMQTL9flzVbEDMVUmJFx3hldMf8
"""


!pip install yfinance groq ta torch plotly pandas numpy scikit-learn

import yfinance as yf
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import json
import os
import torch
import torch.nn as nn

import ta

from groq import Groq

lstm_lookback=10
lstm_epochs=100

companies = [
"RELIANCE.NS",
"TCS.NS",
"INFY.NS",
"HDFCBANK.NS",
"ICICIBANK.NS",

"ITC.NS",
"LT.NS",
"BHARTIARTL.NS",
"SBIN.NS"
]

def fetch_data():

    all_data = []

    for symbol in companies:

        stock = yf.Ticker(symbol)

        hist = stock.history(period="6mo")

        hist["Symbol"] = symbol

        hist=hist[["Open","High","Low","Close","Volume","Symbol"]]

        all_data.append(hist)

    data = pd.concat([df for df in all_data if not df.empty])

    return data

data = fetch_data()
data

def add_indicators(df):
    """Adds RSI, MACD, Bollinger Bands, EMA to a single stock df"""
    df = df.copy()

    # RSI - momentum
    df['RSI'] = ta.momentum.RSIIndicator(df['Close'], window=14).rsi()

    # MACD - trend
    macd = ta.trend.MACD(df['Close'])
    df['MACD'] = macd.macd()
    df['MACD_signal'] = macd.macd_signal()

    # Bollinger Bands - volatility
    bb = ta.volatility.BollingerBands(df['Close'], window=20)
    df['BB_high'] = bb.bollinger_hband()
    df['BB_low']  = bb.bollinger_lband()
    df['BB_mid']  = bb.bollinger_mavg()

    # EMA 20 - trend baseline
    df['EMA_20'] = ta.trend.EMAIndicator(df['Close'], window=20).ema_indicator()

    # ATR - volatility measure
    df['ATR'] = ta.volatility.AverageTrueRange(
        df['High'], df['Low'], df['Close']
    ).average_true_range()

    df.dropna(inplace=True)
    return df

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,LSTM,Dropout
from sklearn.preprocessing import MinMaxScaler

def trainLSTM(prices,lookback=lstm_lookback,epochs=lstm_epochs):
  scaler=MinMaxScaler()
  scaled=scaler.fit_transform(prices.reshape(-1,1))
  x,y=[],[]
  for i in range(lookback,len(scaled)):
    x.append(scaled[i-lookback:i,0])
    y.append(scaled[i,0])
  x=np.array(x).reshape(-1,lookback,1)
  y=np.array(y)


  model=Sequential([
      LSTM(64, return_sequences=True, input_shape=(lookback,1)),
      Dropout(0.2),
      LSTM(64),
      Dense(1)
  ])
  model.compile(optimizer='adam',loss='mse')
  model.fit(x,y,epochs=lstm_epochs,batch_size=15,verbose=0)
  last_seq = scaled[-lookback:].reshape(1, lookback, 1)
  pred_scaled = model.predict(last_seq, verbose=0)[0][0]

  predicted_price = scaler.inverse_transform([[pred_scaled]])[0][0]
  return predicted_price

client = Groq(api_key="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")

def get_llm_explanation(symbol,current_price,lstm_price,change_pct,trend,rsi,macd):
  prompt=f"""
    You are a freindly and genius financial advisor explaining stocks to a beginner student.
    and tell him like you are the only person in the world who can explain that much easily and
    make him beginner to advanced levelis  just only you
    Company: {symbol}
    Current Price: ₹{current_price}
    LSTM Predicted Price: ₹{lstm_price}
    Expected Change: {change_pct}%
    Trend: {trend}
    RSI (momentum): {rsi:.1f} — above 70 means overbought, below 30 means oversold
    MACD: {macd:.2f} — positive means bullish momentum

    Explain this in 4-5 simple sentences a student with zero finance knowledge can understand.
    Mention what RSI and MACD are telling us in simple words.
    Be friendly, confident, and encouraging. No complex jargon.
    """
  response=client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "user", "content": prompt}
        ]

    )
  return response.choices[0].message.content

def predict(symbol, data):
    stock_data = data[data["Symbol"] == symbol].copy()
    stock_data = add_indicators(stock_data)

    prices = stock_data["Close"].values
    current_price = prices[-1]

    # --- LSTM only ---
    lstm_price = trainLSTM(prices, lookback=lstm_lookback, epochs=lstm_epochs)
    if lstm_price is None:
        lstm_price = current_price  # fallback to current if not enough data

    predicted_price = lstm_price

    change_pct = ((predicted_price - current_price) / current_price) * 100

    if change_pct > 0.3:
        trend = "Upward 📈"
    elif change_pct < -0.3:
        trend = "Downward 📉"
    else:
        trend = "Stable ➡️"

    rsi  = stock_data["RSI"].iloc[-1]
    macd = stock_data["MACD"].iloc[-1]

    explanation = get_llm_explanation(
        symbol=symbol,
        current_price=round(float(current_price), 2),
        lstm_price=round(float(lstm_price), 2),      # ✅ removed lr_price
        change_pct=round(float(change_pct), 2),
        trend=trend,
        rsi=rsi,
        macd=macd
    )

    return {
        "symbol": symbol,
        "current_price": round(float(current_price), 2),
        "predicted_price": round(float(predicted_price), 2),  # ✅ removed lr_predicted
        "change_percent": round(float(change_pct), 2),
        "trend": trend,
        "rsi": round(float(rsi), 2),
        "macd": round(float(macd), 2),
        "AI_explanation": explanation,
        "history": stock_data  # for charts
    }

def generate_charts(result):
    df = result["history"]
    symbol = result["symbol"]
    charts = {}

    # --- Chart 1: Candlestick + Bollinger Bands + EMA + RSI + MACD ---
    fig1 = make_subplots(rows=3, cols=1, shared_xaxes=True,
                         row_heights=[0.6, 0.2, 0.2],
                         subplot_titles=[f"{symbol} Price + Bollinger Bands", "RSI", "MACD"])

    fig1.add_trace(go.Candlestick(
        x=df.index, open=df['Open'], high=df['High'],
        low=df['Low'], close=df['Close'], name="Price"
    ), row=1, col=1)

    fig1.add_trace(go.Scatter(x=df.index, y=df['BB_high'], name="BB High",
                              line=dict(color='rgba(173,216,230,0.5)'), showlegend=False), row=1, col=1)
    fig1.add_trace(go.Scatter(x=df.index, y=df['BB_low'], name="BB Low",
                              fill='tonexty', fillcolor='rgba(173,216,230,0.1)',
                              line=dict(color='rgba(173,216,230,0.5)'), showlegend=False), row=1, col=1)
    fig1.add_trace(go.Scatter(x=df.index, y=df['EMA_20'], name="EMA 20",
                              line=dict(color='orange', width=1.5)), row=1, col=1)

    # RSI
    fig1.add_trace(go.Scatter(x=df.index, y=df['RSI'], name="RSI",
                              line=dict(color='purple')), row=2, col=1)
    fig1.add_hline(y=70, line_dash="dash", line_color="red", row=2, col=1)
    fig1.add_hline(y=30, line_dash="dash", line_color="green", row=2, col=1)

    # MACD
    fig1.add_trace(go.Scatter(x=df.index, y=df['MACD'], name="MACD",
                              line=dict(color='blue')), row=3, col=1)
    fig1.add_trace(go.Scatter(x=df.index, y=df['MACD_signal'], name="Signal",
                              line=dict(color='red')), row=3, col=1)

    fig1.update_layout(title=f"{symbol} — Full Technical Analysis",
                       xaxis_rangeslider_visible=False, height=700,
                       template="plotly_dark")

    charts["technical_chart"] = fig1.to_json()

    # --- Chart 2: Price History + LSTM Prediction Point ---
    fig2 = go.Figure()
    fig2.add_trace(go.Scatter(
        x=df.index[-30:], y=df['Close'].values[-30:],
        mode='lines+markers', name='Close Price',
        line=dict(color='#00d4ff', width=2)
    ))
    fig2.add_trace(go.Scatter(
        x=[df.index[-1] + pd.Timedelta(days=1)],
        y=[result["predicted_price"]],
        mode='markers+text',
        marker=dict(size=14, color='yellow', symbol='star'),
        text=[f"₹{result['predicted_price']}"],
        textposition="top center",
        name='LSTM Predicted'                          # ✅ removed LR trace
    ))
    fig2.update_layout(title=f"{symbol} — 30 Day Price + LSTM Prediction",
                       xaxis_title="Date", yaxis_title="Price (₹)",
                       template="plotly_dark", height=400)

    charts["prediction_chart"] = fig2.to_json()

    # --- Chart 3: Volume Bar ---
    fig3 = go.Figure()
    fig3.add_trace(go.Bar(
        x=df.index[-30:], y=df['Volume'].values[-30:],
        marker_color='steelblue', name='Volume'
    ))
    fig3.update_layout(title=f"{symbol} — Volume (Last 30 Days)",
                       template="plotly_dark", height=300)

    charts["volume_chart"] = fig3.to_json()

    return charts

def run_and_export(symbol):
    print(f"\n🔄 Fetching data...")
    data = fetch_data()

    print(f"🧠 Training models for {symbol}...")
    result = predict(symbol, data)

    print(f"📊 Generating charts...")
    charts = generate_charts(result)

    # Clean result for JSON export (remove df)
    export = {k: v for k, v in result.items() if k != "history"}
    export["charts"] = charts

    # Save to JSON — your frontend can consume this directly
    with open(f"{symbol.replace('.', '_')}_result.json", "w") as f:
        json.dump(export, f, indent=2)

    print(f"\n✅ Done! Results saved to {symbol.replace('.', '_')}_result.json")
    print(f"\n{'='*50}")
    print(f"Symbol:           {result['symbol']}")
    print(f"Current Price:    ₹{result['current_price']}")
    print(f"Predicted:     ₹{result['predicted_price']}")
    print(f"Change:           {result['change_percent']}%")
    print(f"Trend:            {result['trend']}")
    print(f"RSI:              {result['rsi']}")
    print(f"MACD:             {result['macd']}")
    print(f"\n💬 AI Explanation:")
    print(result['AI_explanation'])

    # Show charts inline in Colab
    from plotly.io import from_json
    from_json(charts["technical_chart"]).show()
    from_json(charts["prediction_chart"]).show()
    from_json(charts["volume_chart"]).show()

    return export


# ============================================================
#   ENTRY POINT
# ============================================================

result = run_and_export("ICICIBANK.NS")
